name: CI

on:
  pull_request:
    branches:
      - main
      - staging
      - release/*
  push:
    branches:
      - main
      - staging
      - release/*

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v2
      - uses: sergeysova/jq-action@v2
      - name: Test Ignite aggregates
        shell: bash
        run: ./testAggregates.sh
